language: node_js
node_js:
  - stable
  - lts/erbium
  - lts/dubnium

env:
  - TYPESCRIPT_VERSION=latest
  - TYPESCRIPT_VERSION=4.0
  - TYPESCRIPT_VERSION=3.9
  - TYPESCRIPT_VERSION=3.8
  - TYPESCRIPT_VERSION=3.7

before_script:
  - npm install --no-save typescript@$TYPESCRIPT_VERSION

after_success:
  - npm run coverage
  - npx nyc report --reporter=text-lcov | npx coveralls
