language: node_js
node_js:
  - node
  - lts/*

env:
  - TYPESCRIPT_VERSION=latest
  - TYPESCRIPT_VERSION=4.0

before_script:
  - npm install --no-save typescript@$TYPESCRIPT_VERSION

after_success:
  - npm run coverage
  - npx nyc report --reporter=text-lcov | npx coveralls
